name: calculator
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  localization: ^0.2.0-nullsafety
  flutter_icons: ^1.1.0
  provider: ^5.0.0
  

dev_dependencies:
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  image: "assets/logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    
localization_dir: assets\lang

  
